// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu2IGPG9jLoAxz3JDzu3rPyIuTnZ5RMtA',
    appId: '1:519920360499:web:022624c9f4077068e89746',
    messagingSenderId: '519920360499',
    projectId: 'docai-78b74',
    authDomain: 'docai-78b74.firebaseapp.com',
    storageBucket: 'docai-78b74.firebasestorage.app',
    measurementId: 'G-G1DS1RB2GF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHCVdZRTpuXR6GxA-cKGigcnrzoWzaS8s',
    appId: '1:519920360499:android:6561f483ccf84484e89746',
    messagingSenderId: '519920360499',
    projectId: 'docai-78b74',
    storageBucket: 'docai-78b74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyY4v3H66CBMhQxgTYpjSXKOKWw_YsmYM',
    appId: '1:519920360499:ios:24d40bb3fddcaeefe89746',
    messagingSenderId: '519920360499',
    projectId: 'docai-78b74',
    storageBucket: 'docai-78b74.firebasestorage.app',
    iosBundleId: 'com.example.docAi',
  );
}
